// <auto-generated />
using System;
using ClassroomEquipmentAccountingEntities.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassroomEquipmentAccountingEntities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620075711_Init_data")]
    partial class Init_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RowCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RowUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Компьютерное оборудование",
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Компьютеры"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Печатающие устройства",
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Принтеры"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Проекционное оборудование",
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Проекторы"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Сетевое оборудование",
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Сеть"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Кабинетная мебель",
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Мебель"
                        });
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RowCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RowUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsHidden = false,
                            ManagerId = 1,
                            Number = "101",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Specialization = "Компьютерный кабинет"
                        },
                        new
                        {
                            Id = 2,
                            IsHidden = false,
                            ManagerId = 1,
                            Number = "102",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Specialization = "Лаборатория сетей"
                        },
                        new
                        {
                            Id = 3,
                            IsHidden = false,
                            ManagerId = 1,
                            Number = "201",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Specialization = "Кабинет программирования"
                        },
                        new
                        {
                            Id = 4,
                            IsHidden = false,
                            ManagerId = 1,
                            Number = "202",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Specialization = "Мультимедийный кабинет"
                        },
                        new
                        {
                            Id = 5,
                            IsHidden = false,
                            ManagerId = 1,
                            Number = "301",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Specialization = "Резервный кабинет"
                        });
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CommissioningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RowCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RowUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("WaranityEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ClassroomId = 1,
                            CommissioningDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryNumber = "INV-0001",
                            IsHidden = false,
                            Model = "Dell OptiPlex 3080",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SN-CPU-0001",
                            Status = 0,
                            WaranityEndDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ClassroomId = 1,
                            CommissioningDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryNumber = "INV-0002",
                            IsHidden = false,
                            Model = "HP LaserJet Pro",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SN-PRT-0002",
                            Status = 0,
                            WaranityEndDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            ClassroomId = 4,
                            CommissioningDate = new DateTime(2021, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryNumber = "INV-0003",
                            IsHidden = false,
                            Model = "Epson EB-X05",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SN-PJT-0003",
                            Status = 0,
                            WaranityEndDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            ClassroomId = 2,
                            CommissioningDate = new DateTime(2018, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryNumber = "INV-0004",
                            IsHidden = false,
                            Model = "Cisco Switch 2960",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SN-NET-0004",
                            Status = 0,
                            WaranityEndDate = new DateTime(2021, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            ClassroomId = 5,
                            CommissioningDate = new DateTime(2017, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryNumber = "INV-0005",
                            IsHidden = false,
                            Model = "Учебный стол Model-A",
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SN-FUR-0005",
                            Status = 0,
                            WaranityEndDate = new DateTime(2020, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.RepairRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RowCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RowUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RepairRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Не включается компьютер",
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Заменить картридж принтера",
                            EndDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Проектор не переключает вход",
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Проблемы в сети, пакетные потери",
                            EndDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Поломка стола",
                            IsHidden = false,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.RepairRequestEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("RepairRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RowUpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RepairRequestId");

                    b.ToTable("RepairRequestEquipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentId = 1,
                            IsHidden = false,
                            RepairRequestId = 1,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EquipmentId = 2,
                            IsHidden = false,
                            RepairRequestId = 2,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EquipmentId = 3,
                            IsHidden = false,
                            RepairRequestId = 3,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EquipmentId = 4,
                            IsHidden = false,
                            RepairRequestId = 4,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            EquipmentId = 5,
                            IsHidden = false,
                            RepairRequestId = 5,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RowUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tag")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Виталий",
                            IsHidden = false,
                            LastName = "Быстров",
                            Login = "login",
                            MiddleName = "Петрович",
                            PasswordHash = "500:Nj5sBszKuiPv9Syy3eV4sg==:D0Z5twb40MEuBiqfdHZbRKVWgZwK4PAeR3XB/VCAjlM=",
                            Permissions = 2097151,
                            RowCreatedAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowUpdateAt = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = 2
                        });
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.Classroom", b =>
                {
                    b.HasOne("ClassroomEquipmentAccountingEntities.Models.User", "Manager")
                        .WithMany("Classrooms")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.Equipment", b =>
                {
                    b.HasOne("ClassroomEquipmentAccountingEntities.Models.Category", "Category")
                        .WithMany("Equipments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomEquipmentAccountingEntities.Models.Classroom", "Classroom")
                        .WithMany("Equipments")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.RepairRequestEquipment", b =>
                {
                    b.HasOne("ClassroomEquipmentAccountingEntities.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomEquipmentAccountingEntities.Models.RepairRequest", "RepairRequest")
                        .WithMany("RepairRequestEquipments")
                        .HasForeignKey("RepairRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("RepairRequest");
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.Category", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.Classroom", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.RepairRequest", b =>
                {
                    b.Navigation("RepairRequestEquipments");
                });

            modelBuilder.Entity("ClassroomEquipmentAccountingEntities.Models.User", b =>
                {
                    b.Navigation("Classrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
