<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FormatConverterLib\FormatConverterLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Images\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Pages\RepairRequestsPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\EquipmentPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\ClassroomsPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pages\CategoryPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
